set_property SRC_FILE_INFO {cfile:c:/Tutorials/Vivado/parvez_ro_during/parvez_ro_during.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0/design_1_processing_system7_0_0_in_context.xdc rfile:../../../parvez_ro_during.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0/design_1_processing_system7_0_0_in_context.xdc id:1 order:EARLY scoped_inst:design_1_i/processing_system7_0} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Tutorials/Vivado/parvez_ro_during/parvez_ro_during.srcs/constrs_1/new/constraints_5x3_ROs.xdc rfile:../../../parvez_ro_during.srcs/constrs_1/new/constraints_5x3_ROs.xdc id:2} [current_design]
current_instance design_1_i/processing_system7_0
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
current_instance
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells design_1_i/RO0/inst/RO[2].nolabel_line95/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y131 [get_cells design_1_i/RO0/inst/RO[2].nolabel_line95/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/RO0/inst/RO[2].notGate[6].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y131 [get_cells {design_1_i/RO0/inst/RO[2].notGate[6].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/RO0/inst/RO[2].notGate[5].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y131 [get_cells {design_1_i/RO0/inst/RO[2].notGate[5].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/RO0/inst/RO[2].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y131 [get_cells {design_1_i/RO0/inst/RO[2].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/RO0/inst/RO[2].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y131 [get_cells {design_1_i/RO0/inst/RO[2].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/RO0/inst/RO[2].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y131 [get_cells {design_1_i/RO0/inst/RO[2].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/RO0/inst/RO[2].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y131 [get_cells {design_1_i/RO0/inst/RO[2].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/RO0/inst/RO[2].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y131 [get_cells {design_1_i/RO0/inst/RO[2].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells design_1_i/RO0/inst/RO[1].nolabel_line95/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y132 [get_cells design_1_i/RO0/inst/RO[1].nolabel_line95/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/RO0/inst/RO[1].notGate[6].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y132 [get_cells {design_1_i/RO0/inst/RO[1].notGate[6].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/RO0/inst/RO[1].notGate[5].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y132 [get_cells {design_1_i/RO0/inst/RO[1].notGate[5].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/RO0/inst/RO[1].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y132 [get_cells {design_1_i/RO0/inst/RO[1].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/RO0/inst/RO[1].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y132 [get_cells {design_1_i/RO0/inst/RO[1].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/RO0/inst/RO[1].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y132 [get_cells {design_1_i/RO0/inst/RO[1].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/RO0/inst/RO[1].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y132 [get_cells {design_1_i/RO0/inst/RO[1].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/RO0/inst/RO[1].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y132 [get_cells {design_1_i/RO0/inst/RO[1].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells design_1_i/RO0/inst/RO[0].nolabel_line95/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y133 [get_cells design_1_i/RO0/inst/RO[0].nolabel_line95/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/RO0/inst/RO[0].notGate[6].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y133 [get_cells {design_1_i/RO0/inst/RO[0].notGate[6].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/RO0/inst/RO[0].notGate[5].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y133 [get_cells {design_1_i/RO0/inst/RO[0].notGate[5].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/RO0/inst/RO[0].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y133 [get_cells {design_1_i/RO0/inst/RO[0].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/RO0/inst/RO[0].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y133 [get_cells {design_1_i/RO0/inst/RO[0].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/RO0/inst/RO[0].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y133 [get_cells {design_1_i/RO0/inst/RO[0].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/RO0/inst/RO[0].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y133 [get_cells {design_1_i/RO0/inst/RO[0].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/RO0/inst/RO[0].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y133 [get_cells {design_1_i/RO0/inst/RO[0].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/RO0/inst/RO[0].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/RO0/inst/RO[1].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/RO0/inst/RO[2].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/RO0/inst/RO[3].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/RO0/inst/RO[4].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/RO0/inst/RO[5].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells design_1_i/RO3/inst/RO[2].nolabel_line95/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y134 [get_cells design_1_i/RO3/inst/RO[2].nolabel_line95/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/RO3/inst/RO[2].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y134 [get_cells {design_1_i/RO3/inst/RO[2].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/RO3/inst/RO[2].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y134 [get_cells {design_1_i/RO3/inst/RO[2].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/RO3/inst/RO[2].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y134 [get_cells {design_1_i/RO3/inst/RO[2].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/RO3/inst/RO[2].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y134 [get_cells {design_1_i/RO3/inst/RO[2].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/RO3/inst/RO[2].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y134 [get_cells {design_1_i/RO3/inst/RO[2].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells design_1_i/RO3/inst/RO[1].nolabel_line95/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y135 [get_cells design_1_i/RO3/inst/RO[1].nolabel_line95/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/RO3/inst/RO[1].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y135 [get_cells {design_1_i/RO3/inst/RO[1].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/RO3/inst/RO[1].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y135 [get_cells {design_1_i/RO3/inst/RO[1].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/RO3/inst/RO[1].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y135 [get_cells {design_1_i/RO3/inst/RO[1].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/RO3/inst/RO[1].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y135 [get_cells {design_1_i/RO3/inst/RO[1].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/RO3/inst/RO[1].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y135 [get_cells {design_1_i/RO3/inst/RO[1].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells design_1_i/RO3/inst/RO[0].nolabel_line95/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y136 [get_cells design_1_i/RO3/inst/RO[0].nolabel_line95/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/RO3/inst/RO[0].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y136 [get_cells {design_1_i/RO3/inst/RO[0].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/RO3/inst/RO[0].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y136 [get_cells {design_1_i/RO3/inst/RO[0].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/RO3/inst/RO[0].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y136 [get_cells {design_1_i/RO3/inst/RO[0].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/RO3/inst/RO[0].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y136 [get_cells {design_1_i/RO3/inst/RO[0].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/RO3/inst/RO[0].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y136 [get_cells {design_1_i/RO3/inst/RO[0].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/RO3/inst/RO[0].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/RO3/inst/RO[1].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/RO3/inst/RO[2].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/RO3/inst/RO[3].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/RO3/inst/RO[4].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/RO3/inst/RO[5].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells design_1_i/RO4/inst/RO[2].nolabel_line95/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y137 [get_cells design_1_i/RO4/inst/RO[2].nolabel_line95/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/RO4/inst/RO[2].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y137 [get_cells {design_1_i/RO4/inst/RO[2].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/RO4/inst/RO[2].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y137 [get_cells {design_1_i/RO4/inst/RO[2].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/RO4/inst/RO[2].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y137 [get_cells {design_1_i/RO4/inst/RO[2].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells design_1_i/RO4/inst/RO[1].nolabel_line95/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y137 [get_cells design_1_i/RO4/inst/RO[1].nolabel_line95/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/RO4/inst/RO[1].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y137 [get_cells {design_1_i/RO4/inst/RO[1].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/RO4/inst/RO[1].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y137 [get_cells {design_1_i/RO4/inst/RO[1].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/RO4/inst/RO[1].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X65Y137 [get_cells {design_1_i/RO4/inst/RO[1].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells design_1_i/RO4/inst/RO[0].nolabel_line95/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y138 [get_cells design_1_i/RO4/inst/RO[0].nolabel_line95/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/RO4/inst/RO[0].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y138 [get_cells {design_1_i/RO4/inst/RO[0].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/RO4/inst/RO[0].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y138 [get_cells {design_1_i/RO4/inst/RO[0].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/RO4/inst/RO[0].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y138 [get_cells {design_1_i/RO4/inst/RO[0].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/RO4/inst/RO[0].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/RO4/inst/RO[1].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/RO4/inst/RO[2].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/RO4/inst/RO[3].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/RO4/inst/RO[4].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/RO4/inst/RO[5].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells design_1_i/BTI0/inst/RO[2].nolabel_line97/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X80Y131 [get_cells design_1_i/BTI0/inst/RO[2].nolabel_line97/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/BTI0/inst/RO[2].notGate[6].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X80Y131 [get_cells {design_1_i/BTI0/inst/RO[2].notGate[6].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/BTI0/inst/RO[2].notGate[5].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X80Y131 [get_cells {design_1_i/BTI0/inst/RO[2].notGate[5].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/BTI0/inst/RO[2].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X80Y131 [get_cells {design_1_i/BTI0/inst/RO[2].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/BTI0/inst/RO[2].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X81Y131 [get_cells {design_1_i/BTI0/inst/RO[2].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/BTI0/inst/RO[2].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X81Y131 [get_cells {design_1_i/BTI0/inst/RO[2].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/BTI0/inst/RO[2].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X81Y131 [get_cells {design_1_i/BTI0/inst/RO[2].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/BTI0/inst/RO[2].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X81Y131 [get_cells {design_1_i/BTI0/inst/RO[2].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells design_1_i/BTI0/inst/RO[1].nolabel_line97/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X80Y132 [get_cells design_1_i/BTI0/inst/RO[1].nolabel_line97/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/BTI0/inst/RO[1].notGate[6].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X80Y132 [get_cells {design_1_i/BTI0/inst/RO[1].notGate[6].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/BTI0/inst/RO[1].notGate[5].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X80Y132 [get_cells {design_1_i/BTI0/inst/RO[1].notGate[5].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/BTI0/inst/RO[1].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X80Y132 [get_cells {design_1_i/BTI0/inst/RO[1].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/BTI0/inst/RO[1].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X81Y132 [get_cells {design_1_i/BTI0/inst/RO[1].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/BTI0/inst/RO[1].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X81Y132 [get_cells {design_1_i/BTI0/inst/RO[1].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/BTI0/inst/RO[1].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X81Y132 [get_cells {design_1_i/BTI0/inst/RO[1].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/BTI0/inst/RO[1].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X81Y132 [get_cells {design_1_i/BTI0/inst/RO[1].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells design_1_i/BTI0/inst/RO[0].nolabel_line97/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X80Y133 [get_cells design_1_i/BTI0/inst/RO[0].nolabel_line97/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/BTI0/inst/RO[0].notGate[6].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X80Y133 [get_cells {design_1_i/BTI0/inst/RO[0].notGate[6].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/BTI0/inst/RO[0].notGate[5].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X80Y133 [get_cells {design_1_i/BTI0/inst/RO[0].notGate[5].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/BTI0/inst/RO[0].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X80Y133 [get_cells {design_1_i/BTI0/inst/RO[0].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/BTI0/inst/RO[0].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X81Y133 [get_cells {design_1_i/BTI0/inst/RO[0].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/BTI0/inst/RO[0].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X81Y133 [get_cells {design_1_i/BTI0/inst/RO[0].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/BTI0/inst/RO[0].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X81Y133 [get_cells {design_1_i/BTI0/inst/RO[0].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/BTI0/inst/RO[0].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X81Y133 [get_cells {design_1_i/BTI0/inst/RO[0].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI0/inst/RO[0].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI0/inst/RO[1].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI0/inst/RO[2].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI0/inst/RO[3].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI0/inst/RO[4].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI0/inst/RO[5].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells design_1_i/BTI1/inst/RO[2].nolabel_line97/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X84Y131 [get_cells design_1_i/BTI1/inst/RO[2].nolabel_line97/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/BTI1/inst/RO[2].notGate[6].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X84Y131 [get_cells {design_1_i/BTI1/inst/RO[2].notGate[6].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/BTI1/inst/RO[2].notGate[5].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X84Y131 [get_cells {design_1_i/BTI1/inst/RO[2].notGate[5].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/BTI1/inst/RO[2].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X84Y131 [get_cells {design_1_i/BTI1/inst/RO[2].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/BTI1/inst/RO[2].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X85Y131 [get_cells {design_1_i/BTI1/inst/RO[2].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/BTI1/inst/RO[2].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X85Y131 [get_cells {design_1_i/BTI1/inst/RO[2].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/BTI1/inst/RO[2].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X85Y131 [get_cells {design_1_i/BTI1/inst/RO[2].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/BTI1/inst/RO[2].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X85Y131 [get_cells {design_1_i/BTI1/inst/RO[2].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells design_1_i/BTI1/inst/RO[1].nolabel_line97/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X84Y132 [get_cells design_1_i/BTI1/inst/RO[1].nolabel_line97/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/BTI1/inst/RO[1].notGate[6].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X84Y132 [get_cells {design_1_i/BTI1/inst/RO[1].notGate[6].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/BTI1/inst/RO[1].notGate[5].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X84Y132 [get_cells {design_1_i/BTI1/inst/RO[1].notGate[5].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/BTI1/inst/RO[1].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X84Y132 [get_cells {design_1_i/BTI1/inst/RO[1].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/BTI1/inst/RO[1].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X85Y132 [get_cells {design_1_i/BTI1/inst/RO[1].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/BTI1/inst/RO[1].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X85Y132 [get_cells {design_1_i/BTI1/inst/RO[1].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/BTI1/inst/RO[1].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X85Y132 [get_cells {design_1_i/BTI1/inst/RO[1].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/BTI1/inst/RO[1].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X85Y132 [get_cells {design_1_i/BTI1/inst/RO[1].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells design_1_i/BTI1/inst/RO[0].nolabel_line97/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X84Y133 [get_cells design_1_i/BTI1/inst/RO[0].nolabel_line97/LUT6_2_inst]
set_property src_info {type:XDC file:2 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/BTI1/inst/RO[0].notGate[6].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X84Y133 [get_cells {design_1_i/BTI1/inst/RO[0].notGate[6].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/BTI1/inst/RO[0].notGate[5].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X84Y133 [get_cells {design_1_i/BTI1/inst/RO[0].notGate[5].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/BTI1/inst/RO[0].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X84Y133 [get_cells {design_1_i/BTI1/inst/RO[0].notGate[4].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {design_1_i/BTI1/inst/RO[0].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X85Y133 [get_cells {design_1_i/BTI1/inst/RO[0].notGate[3].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {design_1_i/BTI1/inst/RO[0].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X85Y133 [get_cells {design_1_i/BTI1/inst/RO[0].notGate[2].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {design_1_i/BTI1/inst/RO[0].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X85Y133 [get_cells {design_1_i/BTI1/inst/RO[0].notGate[1].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {design_1_i/BTI1/inst/RO[0].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X85Y133 [get_cells {design_1_i/BTI1/inst/RO[0].notGate[0].Inverter/LUT6_inst}]
set_property src_info {type:XDC file:2 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI1/inst/RO[0].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI1/inst/RO[1].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI1/inst/RO[2].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI1/inst/RO[3].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI1/inst/RO[4].notGate[0].Inverter/out_sig}]
set_property src_info {type:XDC file:2 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets {design_1_i/BTI1/inst/RO[5].notGate[0].Inverter/out_sig}]
